name: kk_movie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  get_it: ^8.2.0
  http: ^1.5.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  go_router: ^16.2.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  chewie: ^1.12.1
  video_player: ^2.10.0
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  intl_utils: ^2.8.11
  build_runner: ^2.7.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_intl:
    enabled: true
    class_name: S
    main_locale: en
    arb_dir: lib/l10n
    output_dir: lib/l10n