// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdpaY-HQDcWgAkfV9zVshZ26-HLtWtEk4',
    appId: '1:182351976362:web:db1cc60912d77ced967dd3',
    messagingSenderId: '182351976362',
    projectId: 'kk-movies-999',
    authDomain: 'kk-movies-999.firebaseapp.com',
    storageBucket: 'kk-movies-999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWz9kSijM69njC9xeaSyxKiU9VsZxKnoQ',
    appId: '1:182351976362:android:d67b35721a2871ce967dd3',
    messagingSenderId: '182351976362',
    projectId: 'kk-movies-999',
    storageBucket: 'kk-movies-999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2BBCFas2i7M88v0iv0ndgS9BLR2_x9gQ',
    appId: '1:182351976362:ios:cca5d501b88115eb967dd3',
    messagingSenderId: '182351976362',
    projectId: 'kk-movies-999',
    storageBucket: 'kk-movies-999.firebasestorage.app',
    iosClientId: '182351976362-qm7qdgttikk3koqjkmq6gja954fkjn22.apps.googleusercontent.com',
    iosBundleId: 'com.example.kkMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2BBCFas2i7M88v0iv0ndgS9BLR2_x9gQ',
    appId: '1:182351976362:ios:cca5d501b88115eb967dd3',
    messagingSenderId: '182351976362',
    projectId: 'kk-movies-999',
    storageBucket: 'kk-movies-999.firebasestorage.app',
    iosClientId: '182351976362-qm7qdgttikk3koqjkmq6gja954fkjn22.apps.googleusercontent.com',
    iosBundleId: 'com.example.kkMovieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdpaY-HQDcWgAkfV9zVshZ26-HLtWtEk4',
    appId: '1:182351976362:web:4774804189f0a6a0967dd3',
    messagingSenderId: '182351976362',
    projectId: 'kk-movies-999',
    authDomain: 'kk-movies-999.firebaseapp.com',
    storageBucket: 'kk-movies-999.firebasestorage.app',
  );
}
